# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
          
# Site settings
title: Richard Border
description: "Predoctoral Fellow, Institute for Behavioral Genetics, University of Colorado Boulder"
#repository: https://github.com/rborder/website
baseurl: ''  #http://localhost
#url:# https://localhost  # the base hostname & protocol for your site

# Build settings 
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: 'markdown' # markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Richard Border
# email: richard.border@colorado.edu

navigation:
  - text: Home
    url: /index
  - text: Vita
    url: /vita
  - text: Teaching
    url: /teaching
  - text: Tools
    url: /tools

projects:
  - name: spacemacs 
    description: A community-driven Emacs distribution.
    link: http://spacemacs.org/
    image: http://spacemacs.org/img/logo.svg
  - name: org-mode
    description: An Emacs major mode for note-taking and planning.
    link: http://orgmode.org/
    image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Org-mode-unicorn.svg/2000px-Org-mode-unicorn.svg.png
  - name: LyX
    image: https://chocolatey.org/content/packageimages/lyx.2.2.0.3.svg
    description: An open-source what-you-see-is-what-you-mean document processor.
    link: https://www.lyx.org
  - name: Fedora Workstation
    description: A community-driven Linux distribution based on RPM binaries.
    image: https://getfedora.org/static/images/logo-color-workstation.png
    link: https://getfedora.org/en/workstation/

social:
  - service: mail
    username: richard.border@colorado.edu
    link: mailto:richard.border@colorado.edu
  - service: stackexchange
    username: buckminster
    link: http://stackexchange.com/users/5231062/buckminster
  - service: github
    username: rborder
    link: https://github.com/rborder
  # - service: twitter
    # username: sobolevn
    # link: https://twitter.com/sobolevn

# Plugins
gems:
  - jekyll-seo-tag
