# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
          
# Site settings
title: Richard Border
description: "Predoctoral Fellow, Institute for Behavioral Genetics, University of Colorado Boulder"
#repository: https://github.com/rborder/website
baseurl: ''  #http://localhost
#url:# https://localhost  # the base hostname & protocol for your site

# Build settings 
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: 'markdown' # markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Richard Border
# email: richard.border@colorado.edu

navigation:
  - text: Home
    url: /index
  - text: Vita
    url: /vita
  - text: Teaching
    url: /teaching
  - text: Tools
    url: /tools

projects:
  - name: spacemacs 
    description: A community-driven Emacs distribution.
    link: http://spacemacs.org/
    image: http://spacemacs.org/img/logo.svg
  - name: org-mode
    description: An Emacs major mode for note-taking and planning.
    link: http://orgmode.org/
    image: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Org-mode-unicorn.svg/2000px-Org-mode-unicorn.svg.png
  - name: LyX
    image: https://chocolatey.org/content/packageimages/lyx.2.2.0.3.svg
    description: An open-source what-you-see-is-what-you-mean document processor.
    link: https://www.lyx.org
  - name: Fedora Workstation
    description: A community-driven Linux distribution based on RPM binaries.
    image: https://getfedora.org/static/images/logo-color-workstation.png
    link: https://getfedora.org/en/workstation/
  - name: Julia
    description: A high-level, high-performance scientific programming language.
    image: https://camo.githubusercontent.com/e1ae5c7f6fe275a50134d5889a68f0acdd09ada8/687474703a2f2f6a756c69616c616e672e6f72672f696d616765732f6c6f676f5f68697265732e706e67
    link: http://julialang.org/
  - name: The R Project
    description: A free software environment for statistical computing and graphics. 
    image: https://www.r-project.org/Rlogo.png
    link: https://www.r-project.org/
  - name: Anki
    description: Powerful, intelligent flash cards spaced repetitions.
    image: https://static1.squarespace.com/static/55295a2be4b031351c16468a/t/55745809e4b0888fee5da08d/1433688076531/
    link: https://apps.ankiweb.net
  - name: Friendly Interactive SHell
    description: Finally, a command line shell for the 90s.
    image: http://ridiculousfish.com/shell/images/fishfish_logo.png
    link: https://fishshell.com
  - name: Zotero
    description: Open-source reference management package.
    image: https://www.zotero.org/support/_media/logo/zotero_512x512x32.png
    link: https://www.zotero.org
  - name: GNU Parallel
    description: A shell tool for executing jobs in parallel.
    image: http://www.gnu.org/software/parallel/logo-gray+black300.png
    link: https://www.gnu.org/software/parallel/

social:
  - service: mail
    username: richard.border@colorado.edu
    link: mailto:richard.border@colorado.edu
  - service: stackexchange
    username: buckminster
    link: http://stackexchange.com/users/5231062/buckminster
  - service: github
    username: rborder
    link: https://github.com/rborder
  # - service: twitter
    # username: sobolevn
    # link: https://twitter.com/sobolevn

# Plugins
gems:
  - jekyll-seo-tag
