# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
          
# Site settings
title: Richard Border
description: "Predoctoral Fellow, Institute for Behavioral Genetics, University of Colorado Boulder"
#repository: https://github.com/rborder/website
baseurl: ''  #http://localhost
#url:# https://localhost  # the base hostname & protocol for your site

# Build settings 
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: 'markdown' # markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Richard Border
# email: richard.border@colorado.edu

navigation:
  - text: Home
    url: /index
  - text: Vita
    url: /vita
  - text: Teaching
    url: /teaching
  - text: Tools
    url: /tools

projects:
  - name: spacemacs 
    description: A community-driven Emacs distribution.
    link: http://spacemacs.org/
    image: /images/tools/spacemacs.svg
  - name: org-mode
    description: An Emacs major mode for note-taking and planning.
    link: http://orgmode.org/
    image: /images/tools/orgmode.png
  - name: LyX
    image: /images/tools/lyx.svg
    description: Just say no to MS Word.
    link: https://www.lyx.org
  - name: i3 window manager
    description: A tiling window manager for GNU-Linux.
    image: /images/tools/i3wm.png
    link: https://i3wm.org
  # - name: Julia
  #   description: A high-level, high-performance scientific programming language.
  #   image: /images/tools/julia.png
  #   link: http://julialang.org/
  # - name: The R Project
  #   description: A free software environment for statistical computing and graphics. 
  #   image: /images/tools/r.png 
  #   link: https://www.r-project.org/
  # - name: Anki
  #   description: Powerful, intelligent flash cards spaced repetitions.
  #   image: /images/tools/anki.png
  #   link: https://apps.ankiweb.net
  - name: Friendly Interactive SHell
    description: Finally, a command line shell for the 90s.
    image: /images/tools/fish.png 
    link: https://fishshell.com
  - name: Zotero
    description: Open-source reference management package.
    image: /images/tools/zotero.png 
    link: https://www.zotero.org
  # - name: GNU Parallel
  #   description: A shell tool for executing jobs in parallel.
  #   image: /images/tools/gnupar.png 
  #   link: https://www.gnu.org/software/parallel/

social:
  - service: mail
    username: richard.border@colorado.edu
    link: mailto:richard.border@colorado.edu
  - service: stackexchange
    username: buckminster
    link: http://stackexchange.com/users/5231062/buckminster
  - service: github
    username: rborder
    link: https://github.com/rborder
  # - service: twitter
    # username: sobolevn
    # link: https://twitter.com/sobolevn

# Plugins
gems:
  - jekyll-seo-tag
