baseURL = 'https://richardborder.com/'
title = 'border.lab @ CMU'
disableKinds = ["taxonomy", "term"]

[params]
  author = "Richard Border"
  description = "Richard Border's vita"
  favicon = "/favicon.ico"  # path to a .ico to use as favicon
  logo = "/partial_only.svg"  # url or path to a logo to put in the header
  [params.footer]
    text = "copyright richard border 2024"
    url = ""
  [params.style]  # appearance options (can be omitted)
    # fontFamily = "DejaVu Sans"
    fontFamily = "Inconsolata"
    # fontFamily = "Open Sans"
    fontSize = "12pt"
    pageWidth = "700px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#FF9900"
    logoMaxWidth = "50"
    logoMaxHeight = "50px"
    logoOffset = "-5px"
    titleOffset = "5px"
  # [[params.socialIcons]]
  #   icon = "fas fa-envelope"
  #   title = "E-mail"
  #   url = "mailto:border.richard@gmail.com"
  # [[params.socialIcons]]
  #   icon = "ai ai-google-scholar"
  #   title = "Google scholar"
  #   url = "https://scholar.google.com/citations?user=z11Dt0UAAAAJ"
  # [[params.socialIcons]]
  #   icon = "fa-brands fa-github"
  #   title = "github"
  #   url = "https://github.com/rborder"
  # [[params.socialIcons]]
  #   icon = "ai ai-orcid"
  #   title = "Orcid ID"
  #   url = "http://www.orcid.org/0000-0002-6293-2968"



[menu]
  [[menu.main]]
    name = "news"
    url = "/news"
    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    # pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
    weight = 1

  [[menu.main]]
    name = "publications"
    url = "/publications"
    weight = 2
      [[menu.main]]
    name = "people"
    url = "/people"
    weight = 3
   [[menu.main]]
    name = "join"
    url = "/join"
    weight = 4
   [[menu.main]]
    name = "contact"
    url = "/join"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

[permalinks]
  "/" = "/:filename"
